import { TaskCategory, Task, FinanceCategory, Transaction, WeekDayInfo } from "@/types/orbit";

export const WEEK_DAYS: WeekDayInfo[] = [
  { key: "seg", name: "Segunda-feira", shortName: "SEG", description: "Início de órbita" },
  { key: "ter", name: "Terça-feira", shortName: "TER", description: "Aceleração" },
  { key: "qua", name: "Quarta-feira", shortName: "QUA", description: "Ponto médio orbital" },
  { key: "qui", name: "Quinta-feira", shortName: "QUI", description: "Consolidação" },
  { key: "sex", name: "Sexta-feira", shortName: "SEX", description: "Finalização de missões" },
  { key: "sab", name: "Sábado", shortName: "SÁB", description: "Exploração & Lazer" },
  { key: "dom", name: "Domingo", shortName: "DOM", description: "Recarga & Planejamento" },
];

export const INITIAL_TASK_CATEGORIES: TaskCategory[] = [
  {
    id: "guitarra",
    name: "Guitarra",
    color: "#844DFE",
    bgLight: "bg-zinc-100",
    bgDark: "dark:bg-zinc-800/80",
    textLight: "text-zinc-700",
    textDark: "dark:text-zinc-300",
    borderLight: "border-zinc-200",
    borderDark: "dark:border-zinc-700/60",
    icon: "🎸",
  },
  {
    id: "estudos",
    name: "Estudos",
    color: "#3b82f6",
    bgLight: "bg-zinc-100",
    bgDark: "dark:bg-zinc-800/80",
    textLight: "text-zinc-700",
    textDark: "dark:text-zinc-300",
    borderLight: "border-zinc-200",
    borderDark: "dark:border-zinc-700/60",
    icon: "📚",
  },
  {
    id: "faculdade",
    name: "Faculdade",
    color: "#6366f1",
    bgLight: "bg-zinc-100",
    bgDark: "dark:bg-zinc-800/80",
    textLight: "text-zinc-700",
    textDark: "dark:text-zinc-300",
    borderLight: "border-zinc-200",
    borderDark: "dark:border-zinc-700/60",
    icon: "🎓",
  },
  {
    id: "exercicios",
    name: "Exercícios",
    color: "#f59e0b",
    bgLight: "bg-zinc-100",
    bgDark: "dark:bg-zinc-800/80",
    textLight: "text-zinc-700",
    textDark: "dark:text-zinc-300",
    borderLight: "border-zinc-200",
    borderDark: "dark:border-zinc-700/60",
    icon: "⚡",
  },
  {
    id: "projetos",
    name: "Projetos",
    color: "#06b6d4",
    bgLight: "bg-zinc-100",
    bgDark: "dark:bg-zinc-800/80",
    textLight: "text-zinc-700",
    textDark: "dark:text-zinc-300",
    borderLight: "border-zinc-200",
    borderDark: "dark:border-zinc-700/60",
    icon: "🚀",
  },
  {
    id: "rotina",
    name: "Rotina",
    color: "#10b981",
    bgLight: "bg-zinc-100",
    bgDark: "dark:bg-zinc-800/80",
    textLight: "text-zinc-700",
    textDark: "dark:text-zinc-300",
    borderLight: "border-zinc-200",
    borderDark: "dark:border-zinc-700/60",
    icon: "🌿",
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Treinar escalas pentatônicas e sweep picking",
    description: "45 minutos com metrônomo a 120bpm focado em precisão",
    day: "seg",
    categoryId: "guitarra",
    completed: true,
    priority: "alta",
    time: "19:00",
    createdAt: "2026-09-21T10:00:00Z",
  },
  {
    id: "task-2",
    title: "Leitura do artigo de Inteligência Artificial",
    description: "Capítulo 4 sobre redes neurais e arquitetura transformers",
    day: "seg",
    categoryId: "faculdade",
    completed: true,
    priority: "media",
    time: "14:30",
    createdAt: "2026-09-21T10:00:00Z",
  },
  {
    id: "task-3",
    title: "Treino Upper Body (Peito e Costas)",
    description: "Focar em progressão de carga e descanso adequado",
    day: "seg",
    categoryId: "exercicios",
    completed: true,
    priority: "alta",
    time: "07:30",
    createdAt: "2026-09-21T10:00:00Z",
  },
  {
    id: "task-4",
    title: "Estudo de TypeScript avançado e Generics",
    description: "Resolver 5 exercícios no Type-Challenges",
    day: "ter",
    categoryId: "estudos",
    completed: true,
    priority: "alta",
    time: "20:00",
    createdAt: "2026-09-22T10:00:00Z",
  },
  {
    id: "task-5",
    title: "Tirar solo de 'Comfortably Numb'",
    description: "Segundo solo completo, treinar bends de 1.5 tom",
    day: "ter",
    categoryId: "guitarra",
    completed: false,
    priority: "media",
    time: "18:30",
    createdAt: "2026-09-22T10:00:00Z",
  },
  {
    id: "task-6",
    title: "Entrega do trabalho de Sistemas Operacionais",
    description: "Submeter relatório e código compilado no portal",
    day: "qua",
    categoryId: "faculdade",
    completed: false,
    priority: "alta",
    time: "23:59",
    createdAt: "2026-09-23T10:00:00Z",
  },
  {
    id: "task-7",
    title: "Corrida intervalada 5km",
    description: "Tiros de 400m na esteira ou parque",
    day: "qua",
    categoryId: "exercicios",
    completed: false,
    priority: "media",
    time: "07:00",
    createdAt: "2026-09-23T10:00:00Z",
  },
  {
    id: "task-8",
    title: "Prototipar nova feature do Orbit",
    description: "Modelagem das tabelas do painel financeiro",
    day: "qui",
    categoryId: "projetos",
    completed: false,
    priority: "alta",
    time: "21:00",
    createdAt: "2026-09-23T10:00:00Z",
  },
  {
    id: "task-9",
    title: "Revisão dos acordes com nona e décima primeira",
    description: "Harmonia funcional no braço da guitarra",
    day: "qui",
    categoryId: "guitarra",
    completed: false,
    priority: "baixa",
    time: "19:30",
    createdAt: "2026-09-23T10:00:00Z",
  },
  {
    id: "task-10",
    title: "Revisão semanal de matéria e resumos",
    description: "Organizar flashcards no Anki",
    day: "sex",
    categoryId: "estudos",
    completed: false,
    priority: "media",
    time: "16:00",
    createdAt: "2026-09-23T10:00:00Z",
  },
  {
    id: "task-11",
    title: "Troca de cordas da guitarra e hidratação da escala",
    description: "Encordoamento 0.010 Ernie Ball",
    day: "sab",
    categoryId: "guitarra",
    completed: false,
    priority: "media",
    time: "11:00",
    createdAt: "2026-09-23T10:00:00Z",
  },
  {
    id: "task-12",
    title: "Organização geral do quarto e mesa de estudos",
    description: "Limpar setup e cabos",
    day: "dom",
    categoryId: "rotina",
    completed: false,
    priority: "baixa",
    time: "15:00",
    createdAt: "2026-09-23T10:00:00Z",
  },
];

export const INITIAL_FINANCE_CATEGORIES: FinanceCategory[] = [
  { id: "salario", name: "Salário / Proventos", type: "income", color: "#10b981", icon: "💰" },
  { id: "freelance", name: "Freelance & Consultoria", type: "income", color: "#06b6d4", icon: "💻" },
  { id: "investimentos-inc", name: "Rendimentos / Dividendos", type: "income", color: "#8b5cf6", icon: "📈" },
  { id: "moradia", name: "Moradia & Contas", type: "expense", color: "#6366f1", icon: "🏠", monthlyBudget: 1600 },
  { id: "alimentacao", name: "Alimentação & Mercado", type: "expense", color: "#f59e0b", icon: "🍔", monthlyBudget: 850 },
  { id: "transporte", name: "Transporte & Mobilidade", type: "expense", color: "#3b82f6", icon: "🚗", monthlyBudget: 350 },
  { id: "lazer", name: "Lazer & Cultura", type: "expense", color: "#ec4899", icon: "🎮", monthlyBudget: 400 },
  { id: "educacao", name: "Educação & Cursos", type: "expense", color: "#a855f7", icon: "🎓", monthlyBudget: 300 },
  { id: "equipamentos", name: "Música & Equipamentos", type: "expense", color: "#e11d48", icon: "🎸", monthlyBudget: 500 },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    description: "Salário Mensal Tech Corp",
    amount: 6200.0,
    type: "income",
    categoryId: "salario",
    date: "2026-09-05",
    paymentMethod: "transferencia",
    notes: "Depósito líquido mensal",
  },
  {
    id: "tx-2",
    description: "Projeto Frontend Freelancer",
    amount: 1450.0,
    type: "income",
    categoryId: "freelance",
    date: "2026-09-15",
    paymentMethod: "pix",
    notes: "Primeira etapa entregue",
  },
  {
    id: "tx-3",
    description: "Aluguel e Condomínio",
    amount: 1400.0,
    type: "expense",
    categoryId: "moradia",
    date: "2026-09-10",
    paymentMethod: "boleto",
    notes: "Mês de Setembro",
  },
  {
    id: "tx-4",
    description: "Supermercado Mensal",
    amount: 540.35,
    type: "expense",
    categoryId: "alimentacao",
    date: "2026-09-12",
    paymentMethod: "cartao",
    notes: "Compras do mês",
  },
  {
    id: "tx-5",
    description: "Pedal de Efeito Overdrive",
    amount: 380.0,
    type: "expense",
    categoryId: "equipamentos",
    date: "2026-09-18",
    paymentMethod: "pix",
    notes: "Pedal Boss usado em perfeito estado",
  },
  {
    id: "tx-6",
    description: "Mensalidade Faculdade",
    amount: 280.0,
    type: "expense",
    categoryId: "educacao",
    date: "2026-09-08",
    paymentMethod: "boleto",
  },
  {
    id: "tx-7",
    description: "Combustível e Estacionamento",
    amount: 165.5,
    type: "expense",
    categoryId: "transporte",
    date: "2026-09-19",
    paymentMethod: "cartao",
  },
  {
    id: "tx-8",
    description: "Cinema e Restaurante com amigos",
    amount: 145.0,
    type: "expense",
    categoryId: "lazer",
    date: "2026-09-20",
    paymentMethod: "pix",
  },
  {
    id: "tx-9",
    description: "Dividendos FIIs e Ações",
    amount: 215.8,
    type: "income",
    categoryId: "investimentos-inc",
    date: "2026-09-16",
    paymentMethod: "transferencia",
  },
];
